version: "{build}-{branch}"

environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "Stable"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
