version: "{build}-{branch}"

environment:
  matrix:
    - nodejs_version: "7.9.0" # For Electron 1.7.x
    - nodejs_version: "8"
    - nodejs_version: "Stable"
    # - nodejs_version: "LTS"
install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
